language: rust
cache: cargo
sudo: false
rust:
  - stable
  - nightly
os:
  - linux
  # - osx
script:
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then
      cargo build --verbose --features "nightly";
      cargo build --verbose --no-default-features --features "serde-all nightly"
    fi
  - cargo build --verbose;
  - cargo test --verbose;
  - cargo build --verbose --no-default-features serde-all
