language: rust
cache: cargo
sudo: false
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  # - osx
script:
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then
      cargo build --verbose --features "nightly";
      cargo test --verbose --features "nightly";
    else
      cargo build --verbose;
    fi
      # FIXME: when procedural macros stabilize
      # cargo test --verbose;
    #fi
