language: rust
cache: cargo
sudo: false
rust:
  - stable
  - nightly
os:
  - linux
  # - osx
script:
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then
      cargo build --verbose --features all;
      cargo test --verbose --features all;
    else
      cargo build --verbose;
    fi
      # FIXME: when procedural macros stabilize
      # cargo test --verbose;
    #fi
