language: rust
cache: cargo
sudo: false
rust:
  - stable
  - nightly
branches:
  except:
    - proc_macro
matrix:
  allow_failures:
    - rust: nightly
script:
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then
      cargo build --verbose --features "nightly";
      cargo test --verbose --features "nightly";
      (cd service-attr && cargo test --verbose);
      cargo build --verbose --features "nightly clippy";
    fi
  - cargo build --verbose;
  - cargo test --verbose;
  - cargo build --verbose
