[package]
name = "anterofit"
version = "0.0.1"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]

[dependencies]
futures = "0.1.3"
hyper = "0.9.12"
mime = ">= 0.2.2, < 0.3"
multipart = "0.9.0-alpha.2"
quick-error = "1.1.0"
serde = "0.8"
url = "1.0"

threadpool = { version = "*", optional = true }

serde_json = {version = "0.8.3", optional = true }

serde_derive = { version = "0.8", optional = true }

[features]
default = ["json"]
json = ["serde_json"]
pool = ["threadpool"]
nightly = ["serde_derive"]


