[package]
name = "anterofit"
version = "0.1.0"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]

[dependencies]
futures = "0.1.3"
mime = "*"
multipart = "0.9.0-alpha.1"
quick-error = "1.1.0"
serde = "*"
url = "1.0"

threadpool = { version = "*", optional = true }

serde_json = {version = "*", optional = true }

[dependencies.hyper]
version = "0.9.10"

[dev-dependencies]
serde_derive = "*"

[features]
default = ["json"]
json = ["serde_json"]
pool = ["threadpool"]


