[package]
name = "anterofit-service-attr"
version = "0.1.0"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]

[dependencies]
quote = "0.3"
syn = { version = "0.10", features = ["full"] }

[dev-dependencies]
anterofit = { path = "../" }
rustc-serialize = "*"

[lib]
proc-macro = true